### ISSUE TITLE
Alternative für Snap

### ISSUE THREAD

**Issue by hduelme** [uvulpos/setup-linux-desktop#5]
Linux Mint 20 basiert auf Debian (Ubuntu), unterstützt aber kein Snap, daher währe es gut die Flatpack Alternativen auch anzugeben, falls vorhanden.

Alternativ:
Eigene Anleitungen für Linux Mint erstellen.

**Comment by uvulpos** [comment]
Hallo hduelme,

vielen Dank für dein Feedback unter Linux Mint habe ich die Debian Befehle noch nicht ausprobiert, sondern lediglich unter LMDE. Wenn du die Befehle jetzt schon weißt dann darfst du gerne eine Pull-Request machen mit alternativen Befehlen, ansonsten kümmer ich mich im Laufe des Wochenendes drum.

LG
Tim ~ uVulpos
